### PR TITLE
Ignore the footer and config example, but please not ignore the header alter

### PR DESCRIPTION
**Pull request by tim-hub**
When I config the config file in `menu`,  when I add a new name and link, like,

> NameA: //a.com

When I generate the site, it will show like:

> index.namea

So I do this alter, and I find nothing broken after altering for now.

I hope this can make the theme better.

### CODE REVIEW

**Comment by ppoffice** [comment]
You should add a translation if you want to use a custom menu item.
https://github.com/ppoffice/hexo-theme-hueman/blob/master/languages/en.yml#L1

**Comment by tim-hub** [comment]
Oh. I got it.

However, why do not just ireplace `'index.' + i.toLowerCase()` with `i`

**Comment by ppoffice** [comment]
Because by doing that you will not get proper translations for your menus when you are not using English as your site's locale.

**Comment by tim-hub** [comment]
oh, got it.

**Comment by tim-hub** [comment]
do I need to add the menu items to all translation

**Comment by tim-hub** [comment]
it give me back an error

> YAMLException: bad indentation of a mapping entry at line 9, column 3:

**Comment by ppoffice** [comment]
@tim-hub 
You only add it to the language you use.

> YAMLException: bad indentation of a mapping entry at line 9, column 3:

According to the error message, your should check the indent at line 9. Normally the yaml files in this theme is indented with 4 spaces, not a tab.

**Comment by tim-hub** [comment]
oh, but why I cannot use a tab?

**Comment by tim-hub** [comment]
thanks, it worked.

**Pull request closed without merging**
