### PR TITLE
Bug fix for showing multiple Pages or Categories in the header.

### PR DESCRIPTION
**Pull request by primaryobjects**
This is a bug fix for showing multiple pages or categories in the header. Previously, it would show "index.pageName" instead of just "pageName" in the header. This applies to pages and categories that are added via _config.yml. Here is an example of the bug:

```
# Header
menu:
  Home: /
  About: /about
  Contact: /contact
  404: /404
  Categories:
  One: /about
  Two: /contact
```

Bug screenshot:
hueman_header_page_names

Fix applied:
hueman_header_page_names_fix

### CODE REVIEW

**Comment by ppoffice** [comment]
`__('index.' + i.toLowerCase())` is about using the translations in the main nav.

**Comment by primaryobjects** [comment]
Hey, thanks for looking.

I'm not sure what that means. Why does it show "index." before the name in the nav? After changing it to just "i", the nav names appeared correct. So, it seemed like a bug, but not 100% sure. :)

**Comment by ppoffice** [comment]
This `__('index.' + i.toLowerCase())` points to language files like https://github.com/ppoffice/hexo-theme-hueman/blob/master/languages/en.yml. So if you change this to `i`, you will lose the translations .
A better way to do this is adding your menu items to the corresponding language file.

**Comment by primaryobjects** [comment]
Ok, you're right. I updated my local en.yml to add 'Contact' and this fixed the issue. Thanks.

themes\hueman\languages\en.yml
```
index:
  home: 'Home'
  about: 'About'
  search: 'Search'
  contact: 'Contact'
```

**Pull request closed without merging**
